// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY39R6AzABH4gJtwqpE4P47PvIv0xaNNE',
    appId: '1:13817532631:web:76a4be0b6aa76b728ba092',
    messagingSenderId: '13817532631',
    projectId: 'quickshop-e31ca',
    authDomain: 'quickshop-e31ca.firebaseapp.com',
    storageBucket: 'quickshop-e31ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Xuh0PQZkX9MxbplkOOj1o7n9-rwXtyk',
    appId: '1:13817532631:android:5b857486035d95ee8ba092',
    messagingSenderId: '13817532631',
    projectId: 'quickshop-e31ca',
    storageBucket: 'quickshop-e31ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG6i8J-Ds5pD4aqNOHOy1LclR5220lpOY',
    appId: '1:13817532631:ios:43db680278be854b8ba092',
    messagingSenderId: '13817532631',
    projectId: 'quickshop-e31ca',
    storageBucket: 'quickshop-e31ca.firebasestorage.app',
    iosBundleId: 'com.example.quickshop',
  );
}
